### PR TITLE
chore(build): updgrade all building tools

### PR DESCRIPTION
**Pull request by vvo**

### CODE REVIEW

**Comment by vvo** [comment]
I actually wonder if that's alright to bump such angular dependencies to 6 instead of 5, thoughts @samouss?

**Comment by tkrugg** [comment]
Hi @vvo, did the status of this PR change?

**Comment by vvo** [comment]
@tkrugg you can definitely take it from now on. as I was not an angular expert I did not know the implications of bumping such Angular dependencies.

**Comment by vvo** [comment]
You can either close this and do another one or start from here, no preference (maybe easier to start from 0)

**Pull request closed without merging**
