### PR TITLE
Fixes #246 Remove unused HttpClientModule import in InstantSearch module

### LINKED ISSUE #246: Importing Angular InstantSearch breaks existing HTTP requests
Hi all,

I have successfully implemented the Angular integration into our current app - all is working fine.  I have an issue however that any (non-Algolia) HTTP requests within the app are now failing as the app is now longer sending the JWT token (added via an Interceptor).

I believe this is down to the fact that our app already imports the HTTPClientModule to make these requests.  I found that the InstantSearch module also includes the same module (https://github.com/algolia/angular-instantsearch/blob/develop/src/instantsearch/instantsearch.module.ts) which i narrowed down to be the source of the problem.

I cloned the angular-instantsearch repo and removed the HTTPClientModule import, rebuilt and imported this modified version to our app and all is well - app specific HTTP requests work OK and so does the Aloglia lookup.

In order for us to stay current with updates ideally we don't want to continue using this modified version locally.  Therefore would it be possible to conditionally check for HTTPClientModule and only import it if it has not already been loaded by the parent app?

Thanks.

### PR DESCRIPTION
**Pull request by codebubb**
As discussed in #246.

Have removed the HttpClientModule import, ran SSR example in repo and other examples which compiled and ran OK.

Ran tests locally: `Test Suites: 2 skipped, 19 passed, 19 of 21 total`

Appreciate any further testing / feedback before approval. Thanks.

### CODE REVIEW

**Comment by iam4x** [comment]
LGTM @Haroenv 👍 

Re-tested locally and on netlify, looks fine to me.

**Comment by Haroenv** [comment]
Thanks for your contributions @codebubb, and for reviewing @iam4x 🔥

**Comment by codebubb** [comment]
Hi folks, is there any update on the PR? Do we need to await a release for the changes to be merge? Many thanks :)

**Comment by Haroenv** [comment]
No, this PR is complete

**Comment by codebubb** [comment]
OK, no worries - thanks for the update 👍

**Comment by Haroenv** [comment]
If you're waiting for this to be released, or are blocked by it, let me know :)

**Pull request merged**
