### PR TITLE
Feat/support multiple instances

### LINKED ISSUE #67: Support two <ng-ais-instantsearch> instances on the same page
Use case requested from a customer, having two searches for two different indices on the same page.

### PR DESCRIPTION
**Pull request by iam4x**
This is big change in the way how it works internally, since it can only live one service instance in an Angular application.

It is a breaking change for users who already wrote custom widgets.

### 1. BEFORE

`NgAisInstance` was holding the reference of the InstantSearch.js instance. This service was shared in between widgets so they have the reference to the instance.

### 2. AFTER

~`NgAisInstance` holds multiple InstantSearch.js instances. The correspondant instance is binded on the `<ng-ais-instantsearch>` component~

**Update**: I completely removed the instance service, it's a factory by design in Angular applications. Since we need multiple InstantSearch instances, `<ng-ais-instantsearch>` component is now holding the instance 👍 

Every widgets underneath `<ng-ais-instantsearch>` component are requesting the parent component instance in order to have the reference of the correct InstantSearch.js instance.

```js
import { NgAisInstantSearch } from 'angular-instantsearch'; 

constructor(
    @Inject(forwardRef(() => NgAisInstantSearch)) public instantSearchParent: any
)
```

Then the `BaseWidget` class uses `instantSearchParent` to communicate with the InstantSearch.js instance 👍 

You can now have this in a component:

```html
<!-- Default instance -->
<ng-ais-instantsearch>
	[...widgets]
</ng-ais-instantsearch>

<!-- Second instance -->
<ng-ais-instantsearch instanceName="second">
  [...widgets]
</ng-ais-instantsearch>
```

### TODO

* [x] Support multiple instances
* [x] Tests
* [x] Documentation

Fixes #67

### CODE REVIEW

**Comment by iam4x** [comment]
Deploy preview for *angular-instantsearch* failed.

Built with commit d33aff83c67d6f5c19d4f70e35de9555d74c898f

https://app.netlify.com/sites/angular-instantsearch/deploys/5a70aec492226a01c0ac18f2

**Comment by Haroenv** [comment]
If I une it correctly, does that mean that previously you were not instantiating and instance per component?

**Comment by iam4x** [comment]
@Haroenv exactly, only one instance of InstantSearch was ever created.

**Comment by iam4x** [comment]
I completely removed the InstantSearch Instance Service in the library:

>  it's a factory by design in Angular applications. Since we need multiple InstantSearch instances, `<ng-ais-instantsearch>` component is now holding the instance

**Comment by vvo** [comment]
> <ng-ais-instantsearch> component is now holding the instance 👍

👍

**Pull request merged**
