### PR TITLE
docs(transformItems): clarify the plural and use of TI

### PR DESCRIPTION
**Pull request by Haroenv**
see #114 for reference

cc @Robert-king

### CODE REVIEW

**Comment by francoischalifour** [comment]
How about linking an exhaustive example for `transformItems` hosted on [`doc-code-samples`](https://github.com/algolia/doc-code-samples) (and therefore available on CodeSandbox)?

**Comment by Haroenv** [comment]
The one in InstantSearch.js is too short IMO, it doesn't really explain what its use is. See also #114 here, of multiple people getting confused about it, with the current documentation. This line is taken from InstantSearch.css, where we discussed it, but of course, always open to improvement.

**Comment by francoischalifour** [comment]
Yes, I did read the thread. My concern is that if we start paraphrasing the functions' signatures, we don't add any value.

IMO, an example showing multiple showcases is worth a thousand words.

**Comment by tkrugg** [comment]
I agree with @francoischalifour.
The example @Haroenv posted on https://github.com/algolia/angular-instantsearch/issues/114 seem to have helped so why not change the example in the doc? (or maybe add another example if we're worried of overcomplicating them)

**Comment by Haroenv** [comment]
let's add an extra example everywhere then. You can do that in this PR or another @tkrugg  :)

**Comment by robert-king** [comment]
thanks - extra examples would be good in the documentation.
Would also be great if the docs for each widget linked to the demo for each widget.

**Comment by tkrugg** [comment]
@Haroenv can we drop this line " Takes the items as parameter and expects them back in return." ? IMHO the type `(items) => items`  already contains this information.

**Pull request closed without merging**
