### PR TITLE
Feat/autohidecontainer

### LINKED ISSUE #60: Port `autoHideContainer` option from InstantSearch.js
Add to every widget the `autoHideContainer` option which hides the container when there are no data to render.

### PR DESCRIPTION
**Pull request by iam4x**
Fixes #60

### CODE REVIEW

**Comment by iam4x** [comment]
Deploy preview for *angular-instantsearch* ready!

Built with commit 362e5328120baa261da7f92ac7a547a3df87bce4

https://deploy-preview-61--angular-instantsearch.netlify.com

**Comment by iam4x** [comment]
Deploy preview for *angular-instantsearch* ready!

Built with commit b8f0c49718707adb9de0af2585464028e161e3bf

https://deploy-preview-61--angular-instantsearch.netlify.com

**Comment by iam4x** [comment]
Deploy preview for *angular-instantsearch* ready!

Built with commit f468edc546775a2203123ebf05a3356f06d6743a

https://deploy-preview-61--angular-instantsearch.netlify.com

**Comment by vvo** [comment]
A bit late to the party but I thought such feature would be implemented via the addition of a specific class name "canRefine" at the root level so the user can decide to:
1. Hide the full container (with just some CSS)
2. Gray it/make it look like disabled

cc @ronanlevesque thoughts?

The drawback and comments on autoHideContainer have always been that in some situations you don't just want to hide the container but rather gray it so having the information "canRefine" can be a way to do so.

**Pull request merged**
