### PR TITLE
fix(dependencies): set instantsearch.{js,css} as dev and peer deps

### PR DESCRIPTION
**Pull request by tkrugg**

### CODE REVIEW

**Comment by francoischalifour** [comment]
Can you please give more context and details about this dependency strategy?

**Comment by tkrugg** [comment]
I didn't think there more to say then the title but let me explain what I'm doing:
I discussed with @Haroenv and IIUC, vue-instantsearch will eventually more instantsearchj.js and .css as peer dependencies.

**Comment by Haroenv** [comment]
.css can be optionalDependency. Reason is that otherwise it's likely that the dependency version and user's version (e.g. for history routing) get out of sync. If it's a peer dependency there can only be one. 

We should probably try out what kind of error is thrown if people don't install InstantSearch.js and see if we can give a more elaborate one

**Comment by tkrugg** [comment]
Ok. we should probably do this in a major release. What do you with leave this to later?
I'm thinking I'll just update instantsearch.js for now to get the latest fix and release I minor.

**Comment by francoischalifour** [comment]
This is definitely something that needs to be fully understood and tested before approving. Let's just upgrade the InstantSearch.js dependency for now.

Otherwise I think it's a good idea!

**Comment by samouss** [comment]
It's definitely something to do on a major version. Otherwise every users of Angular InstantSearch that do the next update will have an error about the `instantsearch.js` module being not found. Since we remove the hard dependency it won't be installed anymore. It's now up to them to install it. 

It's a good idea to make the change though but on a major version. To avoid to lost this kind of enhancement we can create an issue (or somewhere else) with a specific tag (next major something like that) to be sure that we don't forgot them.

**Comment by francoischalifour** [comment]
Reminder that the InstantSearch.js upgrade is still not effective. [A user](https://github.com/algolia/instantsearch.js/issues/984#issuecomment-431757257) is still waiting for this.

**Comment by samouss** [comment]
This is not related, we can deduplicate lodash without this changes. The solution was to unpin the production dependencies inside InstantSearch. Now it's done so the dependency should be deduplicate.

**Comment by francoischalifour** [comment]
The original intent of the PR was to solve this issue AFAIR, except that we wanted to change too many things. We can however create another PR for that @tkrugg.

The [InstantSearch.js](https://github.com/algolia/angular-instantsearch/blob/develop/package.json#L94) dependency is still not updated so the problem persists.

**Comment by tkrugg** [comment]
will be done in v3

**Pull request closed without merging**
