### PR TITLE
Feat/add community website boilerplate

### PR DESCRIPTION
**Pull request by iam4x**

### CODE REVIEW

**Comment by iam4x** [comment]
Deploy preview for *angular-instantsearch* failed.

Built with commit 2ef4fa9b085c09c3eb2570f5442f593c482436c9

https://app.netlify.com/sites/angular-instantsearch/deploys/5a860b8d48769b5b65f15a93

**Comment by iam4x** [comment]
Hey @LukyVj I have now the PR created with the website deployed here: 

I have some issues to report so you can help me, I have to do the DocSearch integration:

* Images not loading correctly? Might be only my side.
image

* Font looks off on the next three:
image
image
image

* Image missing in the footer:
image

Would be awesome if you can take care of theses 🙏

**Comment by mthuret** [comment]
@iam4x @LukyVj 

- [ ] I would have expect headers to look more like:

image

instead of just Documentation everywhere. 

- [ ] Title of the site should start with Angular InstantSearch 

- [ ] Sidebar should indicate where we are 

image

- [ ] Can we move the Getting Started into a dedicated section present in the header? 
- [ ] Sidebar is buggy. I believe that the react-is code about this might be the most stable one

image

- [ ] add subtitles into the widgets are: Title, Description, Examples, Attributes, it will help for docsearch. I'm not sure the directive code should be the title of the page. See: 
image


Nice have (not mandatory for the release): 
- [ ] Having next/prev under each guides 
image
- [ ] CTA support: Can't find what you are looking for? Open an issue, we'll get back to you. (see IS.JS
- [ ] add examples for every widgets

**Comment by iam4x** [comment]
I've tried to use the react-instantsearch JS for the sidebar, it's almost the same code and I do have the same issue. But it happens only when you change your browser window size.

**Pull request merged**
