### PR TITLE
fix(docs): revert uglifyjs-webpack-plugin to 1.2.5

### PR DESCRIPTION
**Pull request by samouss**
I tested it locally with this version of UglifyJS I don't have the issue. Let see if it works in the preview!

### CODE REVIEW

**Comment by samouss** [comment]
The change that breaks the build is this one (see below). When I revet the change locally it works.

https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/1521c822259b0d372e96c93d275e61b483e23239/src/index.js#L45-L47

**Comment by francoischalifour** [comment]
What do you think of enforcing the option in there?

https://github.com/algolia/angular-instantsearch/blob/805d40626d852288d93f4534377e4f74714034e5/community-website/src/community-project-boilerplate-docgen/webpack.config.build.js#L15-L17

**Comment by samouss** [comment]
Yep we can enforce the rule to the previous default value:

```js
{
  compress: true
}
```

**Comment by samouss** [comment]
Yes but don't think the issue come from the plugin, the root cause might come from `uglify-es`.

**Comment by Haroenv** [comment]
Nice, love breaking changes in a patch

**Pull request merged**
