### PR TITLE
feat(ErrorHandler): use the Angular ErrorHandler

### LINKED ISSUE #264: Be able to catch InstantSearch error
Right now there is no built-in way to catch error that occurs at the InstantSearch level. Users have to create an custom component scoped under the Provider to get access to the instance and then bind an listener on the error event. Here is [an example](https://codesandbox.io/s/6lvp38pv7n).

A possible solution is to attach a listener on the `error` event by default, then re-throw the error inside Angular to be able to catch it with a custom [`ErrorHandler`](https://angular.io/api/core/ErrorHandler).

### PR DESCRIPTION
**Pull request by Jefiozie**
This feature will use the default Angular Error Handler and provides the
complete Error Object from InstantSearch.
Let me know what you guys think and if I need to make adjustments.

This will resolve #264

### CODE REVIEW

**Comment by Haroenv** [comment]
I think this should come with a guide on "how to catch errors", what do you think?

**Comment by Jefiozie** [comment]
This implementation can only be used when you override the default `ErrorHandler` with your own custom one. You want me to make a guide on how to do this?

**Comment by tkrugg** [comment]
Hi @Jefiozie. Thank you very much for you contribution.
When I read the doc for [ErrorHandler provider](https://angular.io/api/core/ErrorHandler) it's advertising to use ErrorHandler on the NgModule. Isn't this something the user has to add on its own?

**Comment by Jefiozie** [comment]
By default there will be a instance of the `ErrorHandler`. If the user has specific needs to override it (let say for a custom logging service) it will need to  override the default as described in the link you provided.

**Comment by Jefiozie** [comment]
Sure that is not a problem. Where and how do you guys do your test?

**Comment by samouss** [comment]
Actually I realise that we don't have tests at all for this module. You can tried to implement one if you want otherwise it's fine we'll add them later on. Not sure how to correctly implement them right now we have to look a it a bit.

**Comment by tkrugg** [comment]
I believe the [tree shaking tests](https://github.com/algolia/angular-instantsearch/blob/develop/src/__tests__/tree-shaking/tree-shaking.spec.ts#L16-L44) can serve as a base.

**Comment by Jefiozie** [comment]
Thanks will have a look at it, I hope tomorrow 😉.

**Comment by Jefiozie** [comment]
So had a look at the tests. For some reason I never can get the error and I'm getting a lot of other errors on my machine(windows). 

Maybe somebody can help me out on how to do the correct setup? I already copied the Three shaking test but it never throws a error If I implement the error part.

**Comment by Jefiozie** [comment]
Any updates on this?

**Comment by Jefiozie** [comment]
I'm closing this PR if needed we can reopen it and continue developing on it.

**Pull request closed without merging**
